{{- if .Values.serviceAccount.create -}}
{{- include "scion-hub.validate" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scion-hub.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scion-hub.labels" . | nindent 4 }}
  {{- with (include "scion-hub.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
